[package]
name = "asbel"
version = "0.1.0"
edition = "2021"

[dependencies]
asbel_compiler = { path = "../compiler" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0" # For easy error handling in main

[[bin]]
name = "asbel"
path = "src/main.rs"
