[package]
name = "asbel-compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
chumsky = "1.0.0-alpha.8"
ariadne = { version = "0.4.1" }
log = "0.4.22"
pretty_env_logger = "0.5.0"
